# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_out.users_pb2 as users__pb2


class UsersInfoStub(object):
    """Сервер предоставляет информацию о пользователе по id или информацию о всех пользователях
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfoById = channel.unary_unary(
                '/UsersInfo/GetInfoById',
                request_serializer=users__pb2.UserId.SerializeToString,
                response_deserializer=users__pb2.UserInfo.FromString,
                )
        self.GetAllUsersInfo = channel.unary_unary(
                '/UsersInfo/GetAllUsersInfo',
                request_serializer=users__pb2.AllUsersRequest.SerializeToString,
                response_deserializer=users__pb2.AllUsersResponse.FromString,
                )


class UsersInfoServicer(object):
    """Сервер предоставляет информацию о пользователе по id или информацию о всех пользователях
    """

    def GetInfoById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllUsersInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsersInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfoById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfoById,
                    request_deserializer=users__pb2.UserId.FromString,
                    response_serializer=users__pb2.UserInfo.SerializeToString,
            ),
            'GetAllUsersInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllUsersInfo,
                    request_deserializer=users__pb2.AllUsersRequest.FromString,
                    response_serializer=users__pb2.AllUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UsersInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UsersInfo(object):
    """Сервер предоставляет информацию о пользователе по id или информацию о всех пользователях
    """

    @staticmethod
    def GetInfoById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UsersInfo/GetInfoById',
            users__pb2.UserId.SerializeToString,
            users__pb2.UserInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllUsersInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UsersInfo/GetAllUsersInfo',
            users__pb2.AllUsersRequest.SerializeToString,
            users__pb2.AllUsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
