# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\"\x19\n\x06UserId\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\xed\x01\n\x08UserInfo\x12 \n\x04name\x18\x01 \x01(\x0b\x32\x12.UserInfo.FullName\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12%\n\x06\x66\x61mily\x18\x03 \x03(\x0b\x32\x15.UserInfo.FamilyEntry\x1a\x46\n\x08\x46ullName\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x13\n\x0bsecond_name\x18\x03 \x01(\t\x1a\x41\n\x0b\x46\x61milyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.UserInfo.FullName:\x02\x38\x01\"+\n\x10\x41llUsersResponse\x12\x17\n\x04user\x18\x01 \x03(\x0b\x32\t.UserInfo\"%\n\x0f\x41llUsersRequest\x12\x12\n\nmax_result\x18\x01 \x01(\x05\x32\x66\n\tUsersInfo\x12!\n\x0bGetInfoById\x12\x07.UserId\x1a\t.UserInfo\x12\x36\n\x0fGetAllUsersInfo\x12\x10.AllUsersRequest\x1a\x11.AllUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _USERINFO_FAMILYENTRY._options = None
  _USERINFO_FAMILYENTRY._serialized_options = b'8\001'
  _globals['_USERID']._serialized_start=15
  _globals['_USERID']._serialized_end=40
  _globals['_USERINFO']._serialized_start=43
  _globals['_USERINFO']._serialized_end=280
  _globals['_USERINFO_FULLNAME']._serialized_start=143
  _globals['_USERINFO_FULLNAME']._serialized_end=213
  _globals['_USERINFO_FAMILYENTRY']._serialized_start=215
  _globals['_USERINFO_FAMILYENTRY']._serialized_end=280
  _globals['_ALLUSERSRESPONSE']._serialized_start=282
  _globals['_ALLUSERSRESPONSE']._serialized_end=325
  _globals['_ALLUSERSREQUEST']._serialized_start=327
  _globals['_ALLUSERSREQUEST']._serialized_end=364
  _globals['_USERSINFO']._serialized_start=366
  _globals['_USERSINFO']._serialized_end=468
# @@protoc_insertion_point(module_scope)
