name: Lint-Build-Push

on: 
    push:
        branches:
            - main

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker images
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: ${{ vars.DOCKER_USERNAME }}/${{vars.DOCKER_REPOSITORY}}
