name: Lint-Build-Push

on: 
    push:
        branches:
            - main

jobs:
    lint: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code 
              uses: actions/checkout@v4
                    
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: 3.8
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run linter
              run: |
                pip install pylint
                pylint **/*.py

    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker images
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: ${{ vars.DOCKER_USERNAME }}/${{vars.DOCKER_REPOSITORY}}
